version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pruebaPostgre
      - POSTGRES_USER=pruebaPostgre
      - POSTGRES_PASSWORD=pruebaPostgre
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pruebaPostgre
    ports:
      - 5050:80

  web:
    build: .
    command: python djangoDocker/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"    
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
